name: Java CI with Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Create Rust library
      run: |
        mkdir -p src/main/resources/META-INF/native/rustlib/src
        echo '[package]' > src/main/resources/META-INF/native/rustlib/Cargo.toml
        echo 'name = "rustlib"' >> src/main/resources/META-INF/native/rustlib/Cargo.toml
        echo 'version = "0.1.0"' >> src/main/resources/META-INF/native/rustlib/Cargo.toml
        echo 'edition = "2018"' >> src/main/resources/META-INF/native/rustlib/Cargo.toml
        echo '[lib]' >> src/main/resources/META-INF/native/rustlib/Cargo.toml
        echo 'crate-type = ["cdylib"]' >> src/main/resources/META-INF/native/rustlib/Cargo.toml
        echo '[dependencies]' >> src/main/resources/META-INF/native/rustlib/Cargo.toml
        echo 'jni = "0.19.0"' >> src/main/resources/META-INF/native/rustlib/Cargo.toml
        echo 'use jni::sys::jint;' > src/main/resources/META-INF/native/rustlib/src/lib.rs
        echo 'use jni::JNIEnv;' >> src/main/resources/META-INF/native/rustlib/src/lib.rs
        echo 'use jni::objects::JClass;' >> src/main/resources/META-INF/native/rustlib/src/lib.rs
        echo '' >> src/main/resources/META-INF/native/rustlib/src/lib.rs
        echo '#[no_mangle]' >> src/main/resources/META-INF/native/rustlib/src/lib.rs
        echo 'pub extern "system" fn Java_com_example_Bridge_add(env: JNIEnv, class: JClass, a: jint, b: jint) -> jint {' >> src/main/resources/META-INF/native/rustlib/src/lib.rs
        echo '    a + b' >> src/main/resources/META-INF/native/rustlib/src/lib.rs
        echo '}' >> src/main/resources/META-INF/native/rustlib/src/lib.rs
        cd src/main/resources/META-INF/native/rustlib
        cargo build --release

    - name: Move compiled library
      run: |
        mv src/main/resources/META-INF/native/rustlib/target/release/librustlib.so src/main/resources/META-INF/native/

    - name: Run Java application
      run: |
        mvn clean install
        java -Djava.library.path=src/main/resources/META-INF/native -cp target/java-rust-bridge-1.0-SNAPSHOT.jar com.example.Bridge
