name: Java CI with Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Create Rust library
      run: |
        mkdir -p src/main/resources/META-INF/native/rustlib/src
        echo '[package]
name = "rustlib"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.19.0"
' > src/main/resources/META-INF/native/rustlib/Cargo.toml
        echo 'use jni::sys::jint;
use jni::JNIEnv;
use jni::objects::JClass;

#[no_mangle]
pub extern "system" fn Java_com_example_Bridge_add(env: JNIEnv, class: JClass, a: jint, b: jint) -> jint {
    a + b
}' > src/main/resources/META-INF/native/rustlib/src/lib.rs
        cd src/main/resources/META-INF/native/rustlib
        cargo build --release

    - name: Move compiled library
      run: |
        mv src/main/resources/META-INF/native/rustlib/target/release/librustlib.so src/main/resources/META-INF/native/

    - name: Run Java application
      run: |
        mvn clean install
        java -Djava.library.path=src/main/resources/META-INF/native -cp target/java-rust-bridge-1.0-SNAPSHOT.jar com.example.Bridge
